# Netlify configuration file

[build]
  # Base directory - where Netlify will look for the package.json
  base = "is-it-irony"
  
  # Build command - this will be run in the base directory
  command = "npm run build"
  
  # Publish directory - relative to the base directory
  publish = "dist"
  
  # Node version for builds
  environment = { NODE_VERSION = "20" }

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"